### PR TITLE
Remove superfluous comment

### PR DESCRIPTION
**Pull request by DilumAluthge**
This solves part (but not all) of #8.

Specifically, it removes a superfluous comment, as discussed here: https://github.com/JuliaRegistries/GeneralRegistryCI.jl/issues/8#issuecomment-542634516

### CODE REVIEW

**Comment by fredrikekre** [comment]
https://github.com/JuliaRegistries/General/pull/4434#issuecomment-542939547 ?

**Comment by DilumAluthge** [comment]
That is bizarre.

**Comment by DilumAluthge** [comment]
This makes zero sense.

**Comment by DilumAluthge** [comment]
Ah no it makes perfect sense

**Comment by DilumAluthge** [comment]
Because I made a mistake

**Comment by DilumAluthge** [comment]
We use different logic for new package vs new version. And I only fixed new package. Didn’t fix new version.

**Comment by DilumAluthge** [comment]
Will be fixed by https://github.com/JuliaRegistries/RegistryCI.jl/pull/17

**Pull request merged**
