### PR TITLE
Improve code coverage a bit

### PR DESCRIPTION
**Pull request by ericphanson**
- The first commit adds some tests from Base which I should have included in #166.
- The second removes `my_retry_suppress_exceptions` since it doesn't seem to be used anywhere, and is not tested.
- The third attempts to improve coverage in `changed_files.jl` by testing a PR that modifies an extra file belonging to another package. I didn't test this locally though (since its in the integration tests), and it was a little hard to understand how it works so I just mimicked the other similar tests.

By the way, I think it might make sense to enable the codecov check to help ensure PRs maintain coverage; I think that might have reminded me to add those tests to #166.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
> By the way, I think it might make sense to enable the codecov check to help ensure PRs maintain coverage

It actually is enabled, but because the integration tests fail on PRs from forks, the codecov check never reports.

**Comment by DilumAluthge** [comment]
You can see the CodeCov check on the "staging PR" that I made to run the integration tests: https://github.com/JuliaRegistries/RegistryCI.jl/pull/167

Scroll down to the bottom, and next to "DilumAluthge merged commit c50bb29 into master", click on the "View details" button to see all of the checks.

**Comment by ericphanson** [comment]
Ah I see, thanks for the pointer. I see those lines were covered anyway, though I think it's still good to have the unit tests. Not sure why I thought they were uncovered actually, since double-checking codecov I see they were indeed covered.

**Comment by DilumAluthge** [comment]
More tests are always better.

**Comment by ericphanson** [comment]
I'll rebase for #171

**Comment by DilumAluthge** [comment]
You may find it helpful to set up your own test repo and run the integration tests on your local machine. The steps are pretty simple:
1. Set up a test repository. For this example, suppose that this repo is called `ericphanson/FOOTESTREPO`.
2. Make sure that there is some content in the `master` branch of `ericphanson/FOOTESTREPO`. Perhaps just a `README.md` file with a single word or something like that.
3. Set the environment variable: `export AUTOMERGE_INTEGRATION_TEST_REPO="ericphanson/FOOTESTREPO`"`
4. Set the environment variable: `export AUTOMERGE_RUN_INTEGRATION_TESTS="true"`
5. Go to https://github.com/settings/tokens and generate a new GitHub personal access token. Save that token somewhere - I recommend saving the token in a secure location like a password manager.
6. Set the environment variable: `export BCBI_TEST_USER_GITHUB_TOKEN="YOUR_GITHUB_PERSONAL_ACCESS_TOKEN"`
7. Run the package tests `Pkg.test("RegistryCI")`. Watch the logs - you should see the message `AutoMerge.jl integration tests`, which confirms that you are running the integration tests.

Also, it would probably be good for us to document these instructions somewhere so that other people can also run the integration tests on their local machines.

**Comment by DilumAluthge** [comment]
Actually, it would be very helpful for me if you can follow those instructions and confirm that they are correct.

**Comment by DilumAluthge** [comment]
I.e. confirm that you are able to run the integration tests on your local machine by following those instructions.

**Comment by ericphanson** [comment]
Sure, I'll give it a try

**Comment by ericphanson** [comment]
Do you know which permissions are needed for the token?

**Comment by DilumAluthge** [comment]
> Do you know which permissions are needed for the token?

I think you only need `repo`.

**Comment by DilumAluthge** [comment]
So check the `repo` checkbox and check all of the sub-checkboxes under `repo`.

**Comment by ericphanson** [comment]
The instructions worked perfectly! I actually had only checked the `public_repo` sub-checkmark for the token permissions and left everything else unchecked, and that was enough.

I also saw the message 
```julia
┌ Info: Only modifies the files that it's allowed to modify
│   meets_this_guideline = false
└   message = "This pull request modified at least one file that it is not allowed to modify. It is only allowed to modify the following files (or a subset thereof): R/Requires/Compat.toml, R/Requires/Deps.toml, R/Requires/Versions.toml"
```
which I think means my test did what I hoped it would.

**Comment by ericphanson** [comment]
Do you know if somehow I can add that token to Travis so that my PRs (from my fork to this repo) can run the integration tests? (Some secure way, considering it has write permission to all my public repos!)

**Comment by DilumAluthge** [comment]
> Do you know if somehow I can add that token to Travis so that my PRs (from my fork to this repo) can run the integration tests? (Some secure way, considering it has write permission to all my public repos!)

Hmm. That is a great question, but I do not know the answer.

**Pull request merged**
