### PR TITLE
Don't unnecessarily print an error that we are intentionally ignoring

### LINKED ISSUE #311: Error thrown in `delete_merged_branch!` due to GitHub 422 status code
Sorry if this is expected / known / harmless, but: I just noticed that `delete_merged_branch!` throws errors when it is used in the General registry CI.

I was watching https://github.com/JuliaRegistries/General/runs/1597754098?check_suite_focus=true to see when one of my package update PRs got merged... And noticed this error being shown several times (presumably once for each automerged PR?)

```
[ Info: Pull request: 26804. Type: NewVersion. Decision: merge now.
[ Info: Attempting to squash-merge pull request #26804
┌ Debug: sha = 84a2a5d54f5ad1203bc09d88613d36eb69a35849
└ @ RegistryCI.AutoMerge ~/.julia/packages/RegistryCI/Nre1Q/src/AutoMerge/github.jl:140
┌ Debug: pr.mergeable = true
└ @ RegistryCI.AutoMerge ~/.julia/packages/RegistryCI/Nre1Q/src/AutoMerge/github.jl:141
Error found in GitHub reponse:
	Status Code: 422
	Message: Reference does not exist
	Docs URL: https://docs.github.com/rest/reference/git#delete-a-reference
	Errors: 
Stacktrace:
 [1] error(::String, ::String, ::String, ::String, ::String) at ./error.jl:42
 [2] handle_response_error(::HTTP.Messages.Response) at /home/runner/.julia/packages/GitHub/Em3bH/src/utils/requests.jl:177
 [3] github_request(::GitHub.GitHubWebAPI, ::Function, ::String; auth::GitHub.OAuth2, handle_error::Bool, headers::Dict{Any,Any}, params::Dict{Any,Any}, allowredirects::Bool) at /home/runner/.julia/packages/GitHub/Em3bH/src/utils/requests.jl:68
 [4] #gh_delete#7 at /home/runner/.julia/packages/GitHub/Em3bH/src/utils/requests.jl:75 [inlined]
 [5] delete_reference(::GitHub.GitHubWebAPI, ::GitHub.Repo, ::String; options::Base.Iterators.Pairs{Symbol,GitHub.OAuth2,Tuple{Symbol},NamedTuple{(:auth,),Tuple{GitHub.OAuth2}}}) at /home/runner/.julia/packages/GitHub/Em3bH/src/git/reference.jl:31
 [6] delete_merged_branch!(::GitHub.GitHubWebAPI, ::GitHub.Repo, ::GitHub.PullRequest; auth::GitHub.OAuth2) at /home/runner/.julia/packages/RegistryCI/Nre1Q/src/AutoMerge/github.jl:31
 [7] merge!(::GitHub.GitHubWebAPI, ::GitHub.Repo, ::GitHub.PullRequest, ::SubString{String}; auth::GitHub.OAuth2) at /home/runner/.julia/packages/RegistryCI/Nre1Q/src/AutoMerge/github.jl:154
 [8] #57 at /home/runner/.julia/packages/RegistryCI/Nre1Q/src/AutoMerge/cron.jl:352 [inlined]
 [9] (::Base.var"#56#58"{Base.var"#56#57#59"{ExponentialBackOff,Nothing,RegistryCI.AutoMerge.var"#57#59"{GitHub.OAuth2,GitHub.GitHubWebAPI,GitHub.PullRequest,GitHub.Repo,SubString{String}}}})(; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at ./error.jl:288
 [10] (::Base.var"#56#58"{Base.var"#56#57#59"{ExponentialBackOff,Nothing,RegistryCI.AutoMerge.var"#57#59"{GitHub.OAuth2,GitHub.GitHubWebAPI,GitHub.PullRequest,GitHub.Repo,SubString{String}}}})() at ./error.jl:284
 [11] my_retry(::Function, ::Int64) at /home/runner/.julia/packages/RegistryCI/Nre1Q/src/AutoMerge/api_rate_limiting.jl:2 (repeats 2 times)
 [12] cron_or_api_build(::GitHub.GitHubWebAPI, ::GitHub.PullRequest, ::GitHub.Repo; auth::GitHub.OAuth2, authorized_authors::Array{String,1}, authorized_authors_special_jll_exceptions::Array{String,1}, merge_new_packages::Bool, merge_new_versions::Bool, new_package_waiting_period::Day, new_jll_package_waiting_period::Minute, new_version_waiting_period::Minute, new_jll_version_waiting_period::Minute, whoami::String, all_statuses::Array{String,1}, all_check_runs::Array{String,1}) at /home/runner/.julia/packages/RegistryCI/Nre1Q/src/AutoMerge/cron.jl:352
 [13] #52 at /home/runner/.julia/packages/RegistryCI/Nre1Q/src/AutoMerge/cron.jl:217 [inlined]
 [14] (::Base.var"#56#58"{Base.var"#56#57#59"{ExponentialBackOff,Nothing,RegistryCI.AutoMerge.var"#52#54"{GitHub.OAuth2,Array{String,1},Array{String,1},Bool,Bool,Day,Minute,Minute,Minute,String,Array{String,1},Array{String,1},GitHub.GitHubWebAPI,GitHub.Repo,GitHub.PullRequest}}})(; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at ./error.jl:301
 [15] #56 at ./error.jl:284 [inlined]
 [16] my_retry at /home/runner/.julia/packages/RegistryCI/Nre1Q/src/AutoMerge/api_rate_limiting.jl:2 [inlined]
 [17] cron_or_api_build(::GitHub.GitHubWebAPI, ::GitHub.Repo; auth::GitHub.OAuth2, authorized_authors::Array{String,1}, authorized_authors_special_jll_exceptions::Array{String,1}, merge_new_packages::Bool, merge_new_versions::Bool, new_package_waiting_period::Day, new_jll_package_waiting_period::Minute, new_version_waiting_period::Minute, new_jll_version_waiting_period::Minute, whoami::String, all_statuses::Array{String,1}, all_check_runs::Array{String,1}) at /home/runner/.julia/packages/RegistryCI/Nre1Q/src/AutoMerge/cron.jl:217
 [18] run(::Base.EnvDict, ::RegistryCI.AutoMerge.GitHubActions; merge_new_packages::Bool, merge_new_versions::Bool, new_package_waiting_period::Day, new_jll_package_waiting_period::Minute, new_version_waiting_period::Minute, new_jll_version_waiting_period::Minute, registry::String, tagbot_enabled::Bool, authorized_authors::Array{String,1}, authorized_authors_special_jll_exceptions::Array{String,1}, additional_statuses::Array{String,1}, additional_check_runs::Array{String,1}, master_branch::String, master_branch_is_default_branch::Bool, suggest_onepointzero::Bool, registry_deps::Array{String,1}, api_url::String) at /home/runner/.julia/packages/RegistryCI/Nre1Q/src/AutoMerge/public.jl:71
 [19] top-level scope at /home/runner/work/_temp/5d6a8b4d-a327-41d9-8a2a-a9830d2a35d3:4
 [20] include(::Function, ::Module, ::String) at ./Base.jl:380
 [21] include(::Module, ::String) at ./Base.jl:368
 [22] exec_options(::Base.JLOptions) at ./client.jl:296
 [23] _start() at ./client.jl:506
```

### PR DESCRIPTION
**Pull request by DilumAluthge**
Fixes #311

### CODE REVIEW

**Comment by DilumAluthge** [comment]
bors merge

**Comment by ericphanson** [comment]
Is it possible to be more targeted, ie check it’s a 422? Blanket catches scare me...

**Comment by DilumAluthge** [comment]
> Is it possible to be more targeted, ie check it’s a 422? Blanket catches scare me...

That's a good idea.

**Comment by DilumAluthge** [comment]
Probably the laziest way to do it is to just search the error message for the strings "Status Code: 422" and "Message: Reference does not exist".

**Pull request merged**
