### PR TITLE
Regex improvements and regex tests

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
bors try

**Comment by ericphanson** [comment]
it's starting to get more complicated 😅 . Maybe we can add unit tests for this regex? Could just check that `RegistryCI.AutoMerge.commit_regex` matches the right things and misses other things

**Comment by DilumAluthge** [comment]
Good call, I'll add some tests.

**Comment by DilumAluthge** [comment]
bors merge

**Pull request merged**
