### PR TITLE
make RegistryCI tests less reliant on Pkg internals

### PR DESCRIPTION
**Pull request by KristofferC**
The signature changed for this in 1.6 and will further be changed on master. Might make sense to just use a snapshotted copy here.

### CODE REVIEW

**Comment by KristofferC** [comment]
> ERROR: Version number is unchanged, which is not allowed

huh?

**Comment by DilumAluthge** [comment]
Since this PR is a bugfix, I bumped the patch version number.

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
LGTM. Comment `bors merge` whenever you are ready to merge.

**Comment by DilumAluthge** [comment]
bors try

**Comment by DilumAluthge** [comment]
bors merge

**Comment by DilumAluthge** [comment]
Those test failures are not related to this PR.

bors merge

**Comment by DilumAluthge** [comment]
Thanks @KristofferC!

**Pull request merged**
