### PR TITLE
Put approve-comment in the review

### LINKED ISSUE #8: Decrease verbosity
In the web interface you can leave a comment with the approve, does the API allow that? Would send a single notification instead of both https://github.com/JuliaRegistries/General/pull/4422#issuecomment-542615772 and the approve.

### PR DESCRIPTION
**Pull request by fredrikekre**
Put approve-comment in the review instead of as a separate comment, fixes #8.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
I think this is fine for the short-term. It allows us to reduce the number of notifications (on a PR that passes automerge) from 2 to 1.

My goal is to eliminate the PR review approval altogether. So when I do that, I'll remove the `approve` and add back the comment. That's why I commented out those lines, instead of deleting them. The number of notifications will remain 1, it'll just be 1 comment and 0 reviews instead of 0 comments and 1 review.

**Comment by fredrikekre** [comment]
Alright, I thought we should still approve even though what we look for is that status.

**Comment by DilumAluthge** [comment]
Oh I see what you mean.

Yes we can still leave the approval if you find that helpful!

**Comment by DilumAluthge** [comment]
In that case, I should actually remove those commented-out lines, to make the code cleaner/more readable.

**Comment by fredrikekre** [comment]
Can do that later.

**Pull request merged**
