### PR TITLE
Add TagBot fixup feature

### PR DESCRIPTION
**Pull request by christopher-dG**
It's unit tested but I'll run some manual tests too either today or tomorrow. Needs GitHub 5.1.9: https://github.com/JuliaWeb/GitHub.jl/pull/172

### CODE REVIEW

**Comment by christopher-dG** [comment]
bors try

**Comment by christopher-dG** [comment]
This worked fine in a manual test, I'd say if the CI passes we can merge.

**Comment by DilumAluthge** [comment]
Sounds good to me

**Comment by christopher-dG** [comment]
Oh, this is the Pkg servers being super slow. GitHub 5.2 still hasn't propagated.

**Comment by DilumAluthge** [comment]
Let's see if it's updated now.

bors try

**Comment by DilumAluthge** [comment]
@christopher-dG good to merge whenever you want

**Comment by christopher-dG** [comment]
bors merge

**Pull request merged**
