### PR TITLE
Several improvements to the AutoMerge fail comments

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Review by giordano — APPROVED** [review]
I feel like sometimes I'd like to suggest something else in addition to this, but I can't remember what exactly (should take a note), but this is mostly great, especially explaining not to change the version number, see https://github.com/JuliaRegistries/General/pull/28216#issuecomment-762439685

**Comment by DilumAluthge** [comment]
@giordano Can you take a look at the new version of this PR that I just pushed? I realized that saying "don't bump the version" only applies if the AutoMerge issue is not "you skipped a version number".

**Comment by giordano** [comment]
Yep, looks good :+1:

**Comment by DilumAluthge** [comment]
bors merge

**Pull request merged**
