### PR TITLE
More fixes for the `pkgdir_from_depot` and `meets_version_has_osi_license` functions

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Example failure: https://github.com/JuliaRegistries/General/pull/31739

**Comment by DilumAluthge** [comment]
bors merge

**Comment by ericphanson** [comment]
Thanks a lot for the fixes @DilumAluthge. Any ideas why `Pkg.add` is installing more than one version of the package? E.g. in https://github.com/JuliaRegistries/General/runs/2094093271?check_suite_focus=true it has two,
```
┌ Info: 
     Copying registry from `~/work/General/General`
│   pkgdir_parent = "/tmp/jl_TjpUOK/packages/NMFk"
│   all_pkgdir_elements =
│    2-element Vector{String}:
│     "t59Nq"
└     "vJgC8"
```

**Comment by DilumAluthge** [comment]
I have no idea. That is very strange....

**Pull request merged**
