### PR TITLE
TagBot: Handle repos where issues are disabled

### LINKED ISSUE #304: TagBot: handle repos with issues disabled
https://github.com/JuliaRegistries/General/runs/1474921491?check_suite_focus=true

We don't need to come up with a workaround for this, just don't die. I'll take care of this today or tomorrow, just putting this here to make sure I remember.

### PR DESCRIPTION
**Pull request by christopher-dG**
Closes #304

### CODE REVIEW

**Comment by christopher-dG** [comment]
bors try

**Comment by DilumAluthge** [comment]
If this happens, maybe TagBot should post a comment on the general registry pr? Where the contents of the comment are something like "warning, issues are disabled on the repo"?

**Comment by DilumAluthge** [comment]
IDK, that's probably too much work.

**Comment by christopher-dG** [comment]
Maybe in the future, but for now this is so rare that it doesn't really matter.

**Comment by christopher-dG** [comment]
oops, i'll fix the test tomorrow

**Comment by christopher-dG** [comment]
bors merge

**Comment by christopher-dG** [comment]
Oh, the error isn't mine anymore, it's the deprecation in HTTP 🤷 We should get an HTTP release soon so might as well just wait until then and bump HTTP compat.

**Comment by christopher-dG** [comment]
bors try

I think this ought to work now that HTTP 0.9.1 is here

**Comment by christopher-dG** [comment]
bors merge

**Comment by christopher-dG** [comment]
Oh... we're still getting the deprecation warning. That seems wrong.

**Comment by christopher-dG** [comment]
bors merge

PLEASE

**Comment by christopher-dG** [comment]
bors merge ?

**Comment by christopher-dG** [comment]
BLESS

**Pull request merged**
