### PR TITLE
Set `JULIA_PKG_PRECOMPILE_AUTO` env variable

### LINKED ISSUE #400: packages precompile twice during AutoMerge on 1.6
Since they precompile at `Pkg.add` time and we do it twice (with different depots). We should either re-use the depot or prevent precompilation at add time.

### PR DESCRIPTION
**Pull request by ericphanson**
Fixes #400.

I did not bump the version to avoid conflicts with #407

### CODE REVIEW

**Comment by ericphanson** [comment]
I want to run the integration tests to double check it only precompiles at `import` time with this PR.

bors try

**Comment by ericphanson** [comment]
In https://github.com/JuliaRegistries/RegistryCI.jl/runs/2596754467?check_suite_focus=true#step:8:474 from the last merge, it says "precompiling" during the `Pkg.add` step. In https://github.com/JuliaRegistries/RegistryCI.jl/runs/2600851999#step:8:632 from this PR, I don't see any precompiling. So I think it worked!

**Comment by DilumAluthge** [comment]
See the additional commit I pushed.

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
bors try

**Comment by DilumAluthge** [comment]
bors merge

**Comment by ericphanson** [comment]
Thanks @DilumAluthge!

**Pull request merged**
