### PR TITLE
Pass HOME to subprocesses

### LINKED ISSUE #245: LibGit2 callback error in automerge for private registry
With an automerge.yaml set up nearly identically to that used in General, we've been getting the following consistently on our private registry:
```
    Cloning registry from "https://github.com/JuliaRegistries/General.git"
25l    Fetching: [>                                        ]  0.0 %
    Fetching: [=================>                       ]  41.9 %
    Resolving Deltas: [================================>        ]  79.9 %
      Added registry `General` to `/tmp/jl_e18Pfl/registries/General`
25hTest Summary:                                | Pass  Total
(Registry|Package|Versions|Deps|Compat).toml |  287    287
[ Info: Authenticated to GitHub as "github-actions[bot]"
[ Info: Attempting to clone...
[ Info: Attempting to clone...
ERROR: GitError(Code:EUSER, Class:Callback, Aborting, user cancelled credential request.)
Stacktrace:
 [1] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/LibGit2/src/error.jl:101 [inlined]
 [2] clone(::String, ::String, ::LibGit2.CloneOptions) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/LibGit2/src/repository.jl:459
 [3] clone(::String, ::String; branch::String, isbare::Bool, remote_cb::Ptr{Nothing}, credentials::Nothing, callbacks::Dict{Symbol,Tuple{Ptr{Nothing},Any}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/LibGit2/src/LibGit2.jl:580
 [4] clone at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/LibGit2/src/LibGit2.jl:559 [inlined]
 [5] _clone_repo_into_dir(::String, ::String) at /home/runner/.julia/packages/RegistryCI/ZPKNe/src/AutoMerge/util.jl:25
[6] #111 at /home/runner/.julia/packages/RegistryCI/ZPKNe/src/AutoMerge/util.jl:16 [inlined]
 [7] (::Base.var"#58#60"{Base.var"#58#59#61"{ExponentialBackOff,Nothing,RegistryCI.AutoMerge.var"#111#113"{String,String}}})(; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at ./error.jl:301
 [8] #58 at ./error.jl:284 [inlined]
 [9] my_retry at /home/runner/.julia/packages/RegistryCI/ZPKNe/src/AutoMerge/api_rate_limiting.jl:2 [inlined] (repeats 2 times)
 [10] clone_repo(::String) at /home/runner/.julia/packages/RegistryCI/ZPKNe/src/AutoMerge/util.jl:16
 [11] clone_repo at /home/runner/.julia/packages/RegistryCI/ZPKNe/src/AutoMerge/util.jl:10 [inlined]
 [12] pull_request_build(::GitHub.PullRequest, ::String, ::GitHub.Repo, ::String; auth::GitHub.OAuth2, authorized_authors::Array{String,1}, authorized_authors_special_jll_exceptions::Array{String,1}, master_branch::String, master_branch_is_default_branch::Bool, suggest_onepointzero::Bool, whoami::String, registry_deps::Array{String,1}) at /home/runner/.julia/packages/RegistryCI/ZPKNe/src/AutoMerge/pull-requests.jl:88
 [13] pull_request_build(::Int64, ::String, ::GitHub.Repo, ::String; whoami::String, auth::GitHub.OAuth2, authorized_authors::Array{String,1}, authorized_authors_special_jll_exceptions::Array{String,1}, master_branch::String, master_branch_is_default_branch::Bool, suggest_onepointzero::Bool, registry_deps::Array{String,1}) at /home/runner/.julia/packages/RegistryCI/ZPKNe/src/AutoMerge/pull-requests.jl:42
[14] run(::Base.EnvDict, ::RegistryCI.AutoMerge.GitHubActions; merge_new_packages::Bool, merge_new_versions::Bool, new_package_waiting_period::Minute, new_jll_package_waiting_period::Minute, new_version_waiting_period::Minute, new_jll_version_waiting_period::Minute, registry::String, authorized_authors::Array{String,1}, authorized_authors_special_jll_exceptions::Array{String,1}, additional_statuses::Array{String,1}, additional_check_runs::Array{String,1}, master_branch::String, master_branch_is_default_branch::Bool, suggest_onepointzero::Bool, registry_deps::Array{String,1}) at /home/runner/.julia/packages/RegistryCI/ZPKNe/src/AutoMerge/public.jl:50
 [15] top-level scope at none:5
Username for 'https://github.com': Username for 'https://github.com': 
##[error]Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by christopher-dG**
Closes #245 

Lots of stuff needs HOME to work properly.

More concretely, both Git CLI and LibGit2 get their config from `$HOME/.gitconfig` by default, and that breaks when it's unset.

### CODE REVIEW

**Comment by christopher-dG** [comment]
bors try

**Review by DilumAluthge — APPROVED** [review]

**Comment by christopher-dG** [comment]
bors try

**Comment by christopher-dG** [comment]
I've been seeing SimpleMock hanging on nightly for another package, perhaps same thing here.

**Comment by DilumAluthge** [comment]
> I've been seeing SimpleMock hanging on nightly for another package, perhaps same thing here.

If you want, you can add a `VERSION` guard to only run the SimpleMock tests on Julia 1.5.

**Comment by christopher-dG** [comment]
Yeah I'll probably do something like that. I'll get these PRs figured out tomororw.

**Review by fredrikekre — APPROVED** [review]

**Comment by christopher-dG** [comment]
bors merge PLEASE I AM BEGGING YOU

**Comment by christopher-dG** [comment]
@DilumAluthge is there no way for me to not bump the version?

**Comment by DilumAluthge** [comment]
Yeah, comment out the "VersionVigilante" line in the `bors.toml` file.

**Comment by christopher-dG** [comment]
bors merge

**Comment by christopher-dG** [comment]
I am confused as to why this isn't merged now.

**Comment by DilumAluthge** [comment]
Can you go to settings and uncheck VersionVigilante as a required status check?

**Comment by christopher-dG** [comment]
I don't see any setting for that, unfortunately.

**Comment by DilumAluthge** [comment]
(Settings -> branch protection -> master)

Anyway should be good now.

bors merge

**Comment by christopher-dG** [comment]
Oh, I thought you mean in bors settings 🤦

**Pull request merged**
