### PR TITLE
Registry consistency tests: In `Compat.toml`, make sure that each compat spec is a valid registry compat spec

### PR DESCRIPTION
**Pull request by DilumAluthge**
Ref https://github.com/JuliaRegistries/General/issues/104849

### CODE REVIEW

**Comment by DilumAluthge** [comment]
cc: @LilithHafner 

This addresses part of https://github.com/JuliaRegistries/General/issues/104849

**Comment by DilumAluthge** [comment]
Nightly CI failure is https://github.com/JuliaTesting/SimpleMock.jl/issues/20

**Review by ericphanson — APPROVED** [review]

**Comment by DilumAluthge** [comment]
We should probably do the same thing for `WeakCompat.toml` (if it exists).

**Comment by DilumAluthge** [comment]
I'll do that in a follow-up PR.

**Pull request merged**
