### PR TITLE
Add MPIPreferences to list of allowed packages

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Review by giordano — APPROVED** [review]
It's a bit ad-hoc, but probably not too bad

**Comment by vchuravy** [comment]
Is there anything needed to deploy this?

**Comment by giordano** [comment]
If this is in a registered version, I think you need to run this workflow https://github.com/JuliaRegistries/General/actions/workflows/update_manifests.yml

**Comment by DilumAluthge** [comment]
The steps to deploy are:
1. Bump the version number of RegistryCI.jl
2. Register the new version of RegistryCI.jl
3. Wait for the new version of RegistryCI.jl to be auto-merged.
4. Go to https://github.com/JuliaRegistries/General/actions/workflows/update_manifests.yml and trigger a new run of the "Update Manifests" workflow. This opens a PR to `JuliaRegistries/General` to update the manifests we use in CI and AutoMerge.
5. Wait for CI to pass on the "manifest update" PR.
6. Merge the manifest update PR.
7. Profit.

**Pull request merged**
