### PR TITLE
Open tagbot trigger issues for testitem repos

### PR DESCRIPTION
**Pull request by davidanthoff**
Repos that use the `julia-vscode/testitem-workflow/.github/workflows/juliaci.yml` are also TagBot enabled.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Hmmm. So, IIUC, this code is looking for the text `JuliaRegistries/TagBot` in the _contents_ of the file (not the filename).

So I'm wondering why it's not already working, given that the https://github.com/julia-vscode/testitem-workflow/blob/main/.github/workflows/juliaci.yml file already includes the text `JuliaRegistries/TagBot` in the file contents.

**Review by DilumAluthge — APPROVED** [review]

**Comment by ericphanson** [comment]
btw to be deployed, we need to first bump the version and merge & tag that

**Comment by davidanthoff** [comment]
Should I be doing something to trigger that? Probably makes more sense for someone who is more in charge of this repo to do that?

**Comment by ericphanson** [comment]
if it wasn't already merged I'd have asked you to include the version bump as part of the PR. Changes are infrequent currently so IMO it's better to just release whenever there's a change, otherwise it will be a long time until the next release.

**Pull request merged**
