### PR TITLE
In the AutoMerge logs, explain to users that the "Error: Some registries failed to update" and "registry dirty" messages should be ignored

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@giordano What do you think?

**Comment by giordano** [comment]
Is this message close enough to the error messages?  Otherwise I'm worried users won't easily see it.

**Comment by DilumAluthge** [comment]
Good question. Let's do a test run and see what the logs look like.

bors try

**Comment by DilumAluthge** [comment]
IMG_0929

**Comment by giordano** [comment]
Bump?  I thought this was merged, and users are still confused by the error message: https://discourse.julialang.org/t/juliaregistries-cant-update-my-package-because-of-registry-dirty/89379

**Comment by DilumAluthge** [comment]
bors merge

**Comment by DilumAluthge** [comment]
I completely forgot that we never merged this PR. Let's get it in.

**Pull request merged**
