### PR TITLE
allow modifying weak toml files

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/JuliaRegistries/General/pull/75847#issuecomment-1385548064

### CODE REVIEW

**Comment by KristofferC** [comment]
cc @DilumAluthge

**Review by fredrikekre — APPROVED** [review]

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
bors merge

**Comment by DilumAluthge** [comment]
Thanks!

**Comment by DilumAluthge** [comment]
bors merge

**Pull request merged**
